### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by yofreke** [browserify/timers-browserify#29]
My webpack builds started breaking recently, I think because I depend on npm, and npm depends on this.  It could be an issue with my build config, but the builds started breaking around yesterday for me with no changes to our code.

I think the code that is causing our build to fail is the reference to `self` here: https://github.com/browserify/timers-browserify/commit/90cd33279fd77b86bcdebeea307503c43c2831f4#diff-7a9076d6d94e62c13d641aa71f19ae8eR55

My build problems go away with `npm install timers-browserify@2.0.4`

**Comment by jryans** [comment]
Thanks for the report!

Does changing to a check like `typeof self === "undefined"` instead fix the current version for you?

**Comment by yofreke** [comment]
That should do it

**Comment by jryans** [comment]
Okay, I've published a fix as v2.0.6. Let know if that works for you. Thanks for the feedback!

**Comment by yofreke** [comment]
Yup, removed `=2.0.4` from my package.json, build still works.  Thanks for the quick fix!
